from tkinter import *

window = Tk()
window.title("Cryptography")

window1 = Tk()
window1.title("Cryptography")

left_frame = LabelFrame(window, text="John Doe")
left_frame.grid(row=0, column=0, padx=25, pady=50)
right_frame = LabelFrame(window1, text="Jane Doe")
right_frame.grid(row=0, column=1, padx=25, pady=50)

left_label = Label(left_frame, text="Enter Message: ", font=("Courier", 15))
left_message = Text(left_frame, height=5, width=50, font=("Courier", 15))
left_label.grid(row=0, column=0, columnspan=2)
left_message.grid(row=1, column=0, columnspan=2)
key_label = Label(left_frame, text="Public Key: ", font=("Courier", 15))
key_status = Label(left_frame, text="Not Received", font=("Courier", 15), fg="red")
key_label.grid(row=2, column=0)
key_status.grid(row=2, column=1)
left_buttn = Button(left_frame, text="Send Message", fg="gray", font=("Courier", 15))
left_buttn.grid(row=3, column=0, columnspan=2)

right_prLabel = Label(right_frame, text="Private Key: ", width=20, font=("Courier", 15))
right_prEntry = Entry(right_frame, width=30, font=("Courier", 15))
right_prLabel.grid(row=0, column=0)
right_prEntry.grid(row=0, column=1)
right_qLabel = Label(right_frame, text="Prime Number: ", width=20, font=("Courier", 15))
right_qEntry = Entry(right_frame, width=30, font=("Courier", 15))
right_qLabel.grid(row=1, column=0)
right_qEntry.grid(row=1, column=1)
right_aLabel = Label(right_frame, text="Alpha: ", width=20, font=("Courier", 15))
right_aEntry = Entry(right_frame, width=30, font=("Courier", 15))
right_aLabel.grid(row=2, column=0)
right_aEntry.grid(row=2, column=1)
key_buttn = Button(right_frame, text="Generate Public Key and Send", font=("Courier", 15))
key_buttn.grid(row=3, column=0, columnspan=2)
Rec_Label = Label(right_frame, text="Received Message: ", font=("Courier", 15))
Rec_Status = Label(right_frame, text="None", font=("Courier", 15), fg="red")
Rec_Label.grid(row=4, column=0)
Rec_Status.grid(row=4, column=1)
Decrypt_Buttn = Button(right_frame, text="Decrypt Message",  font=("Courier", 15))
Decrypt_Buttn.grid(row=5, column=0, columnspan=2)

window.resizable(0, 0)
window1.resizable(0, 0)
window.mainloop()
window1.mainloop()

